openapi: '3.0.2'
info:
  title: Book API
  version: '1.0'
servers:
  - url: http://localhost:3000

tags:
  - name: Books
    description: Everything about books
  - name: Lends
    description: About lends

paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      responses:
        '200':
          description: OK
    post:
      tags:
        - Books
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Created

  /books/{isbn}:
    get:
      tags:
        - Books
      summary: Get a book by ISBN
      parameters:
        - name: isbn
          in: path
          required: true
          description: The ISBN of the book
          schema:
            type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - Books
      summary: Update a book by ISBN
      parameters:
        - name: isbn
          in: path
          required: true
          description: The ISBN of the book
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Books
      summary: Delete a book by ISBN
      parameters:
        - name: isbn
          in: path
          required: true
          description: The ISBN of the book
          schema:
            type: string
      responses:
        '204':
          description: No Content

  /lends:
    get:
      tags:
        - Lends
      summary: Get all lends
      responses:
        '200':
          description: OK
    post:
      tags:
        - Lends
      summary: Add a new lend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lend'
      responses:
        '201':
          description: Created

  /lends/{id}:
    get:
      tags:
        - Lends
      summary: Get a lend by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the lend
          schema:
            type: integer
      responses:
        '200':
          description: OK
    patch:
      tags:
        - Lends
      summary: Update a lend by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the lend
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lend'
      responses:
        '200':
          description: OK

components:
  schemas:
    Book:
      type: object
      properties:
        titel:
          type: string
          example: "Der Report der Magd"
        autor:
          type: string
          example: "Margaret Atwood"
        isbn:
          type: string
          example: "978-3-498-00679-8"
        erscheinungsjahr:
          type: string
          example: "1985"
    Lend:
      type: object
      properties:
        _id:
          type: integer
          example: 1
        customer_id:
          type: integer
          example: 12345
        isbnborrowed_at:
          type: string
          format: date
          example: "2023-06-01"
        returned_at:
          type: string
          format: date
          example: "2023-06-05"
        isbn:
          type: string
          example: "978-3-16-148410-0"